// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbMvGySq_XO1XyUTGxePrOj6Pe0xCwM9Q',
    appId: '1:41538344528:web:742e409f9f04d162682355',
    messagingSenderId: '41538344528',
    projectId: 'msg-app-625e7',
    authDomain: 'msg-app-625e7.firebaseapp.com',
    storageBucket: 'msg-app-625e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8aL65XKkQVc61P5_LjhWIdGSy9nSvRRc',
    appId: '1:41538344528:android:554c6a3b35b73fb1682355',
    messagingSenderId: '41538344528',
    projectId: 'msg-app-625e7',
    storageBucket: 'msg-app-625e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYG14NGjWYvAy2mIosV2TRHBCCWeebCbY',
    appId: '1:41538344528:ios:da19ef5f2e4cf58d682355',
    messagingSenderId: '41538344528',
    projectId: 'msg-app-625e7',
    storageBucket: 'msg-app-625e7.appspot.com',
    iosBundleId: 'com.example.msgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYG14NGjWYvAy2mIosV2TRHBCCWeebCbY',
    appId: '1:41538344528:ios:b2cb56c13e1cb257682355',
    messagingSenderId: '41538344528',
    projectId: 'msg-app-625e7',
    storageBucket: 'msg-app-625e7.appspot.com',
    iosBundleId: 'com.example.msgApp.RunnerTests',
  );
}
